ALTER TABLE strategy_research_trades
ADD COLUMN IF NOT EXISTS activated_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS status TEXT,
ADD COLUMN IF NOT EXISTS run_id BIGINT,
ADD COLUMN IF NOT EXISTS research_run_id BIGINT,
ADD COLUMN IF NOT EXISTS source TEXT,
ADD COLUMN IF NOT EXISTS timeframe_pair TEXT,
ADD COLUMN IF NOT EXISTS quality_score NUMERIC(8,2),
ADD COLUMN IF NOT EXISTS entry_time TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS level_high NUMERIC(12,3),
ADD COLUMN IF NOT EXISTS level_low NUMERIC(12,3),
ADD COLUMN IF NOT EXISTS level_mid NUMERIC(12,3),
ADD COLUMN IF NOT EXISTS engulf_body_pips NUMERIC(10,2),
ADD COLUMN IF NOT EXISTS engulf_range_pips NUMERIC(10,2),
ADD COLUMN IF NOT EXISTS engulf_type TEXT,
ADD COLUMN IF NOT EXISTS quality_rejection_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS avg_rejection_wick_ratio NUMERIC(10,2),
ADD COLUMN IF NOT EXISTS avg_push_away_pips NUMERIC(10,2),
ADD COLUMN IF NOT EXISTS strongest_rejection_pips NUMERIC(10,2),
ADD COLUMN IF NOT EXISTS rejection_quality_score NUMERIC(8,2),
ADD COLUMN IF NOT EXISTS confirmation_path TEXT,
ADD COLUMN IF NOT EXISTS confirmation_score NUMERIC(8,2),
ADD COLUMN IF NOT EXISTS revisit_time TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS confirmation_time TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS confirmation_candles_used INTEGER,
ADD COLUMN IF NOT EXISTS notes TEXT,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;

ALTER TABLE strategy_research_runs
ADD COLUMN IF NOT EXISTS finished_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS notes TEXT,
ADD COLUMN IF NOT EXISTS funnel_summary JSONB DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS reject_summary JSONB DEFAULT '{}'::jsonb;

ALTER TABLE strategy_research_stats
ADD COLUMN IF NOT EXISTS funnel_summary JSONB DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS reject_summary JSONB DEFAULT '{}'::jsonb;

NOTIFY pgrst, 'reload schema';
