CREATE TABLE IF NOT EXISTS analyst_replay_runs (
id BIGSERIAL PRIMARY KEY,
symbol TEXT NOT NULL DEFAULT 'XAUUSD',
source TEXT DEFAULT 'historical_replay',
started_at TIMESTAMPTZ DEFAULT NOW(),
completed_at TIMESTAMPTZ,
status TEXT DEFAULT 'running',
months INTEGER,
replay_start TIMESTAMPTZ,
replay_end TIMESTAMPTZ,
total_scenarios INTEGER DEFAULT 0,
total_confirmations INTEGER DEFAULT 0,
total_entries INTEGER DEFAULT 0,
total_reviews INTEGER DEFAULT 0,
net_pips NUMERIC(12,2) DEFAULT 0,
summary JSONB DEFAULT '{}'::jsonb,
notes TEXT
);

ALTER TABLE analyst_replay_runs
ADD COLUMN IF NOT EXISTS symbol TEXT DEFAULT 'XAUUSD',
ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'historical_replay',
ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'running',
ADD COLUMN IF NOT EXISTS months INTEGER,
ADD COLUMN IF NOT EXISTS replay_start TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS replay_end TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS total_scenarios INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_confirmations INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_entries INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_reviews INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS net_pips NUMERIC(12,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS summary JSONB DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS notes TEXT;

CREATE TABLE IF NOT EXISTS analyst_scenario_history (
id BIGSERIAL PRIMARY KEY,
run_id BIGINT,
symbol TEXT NOT NULL DEFAULT 'XAUUSD',
scenario_key TEXT,
source TEXT DEFAULT 'live',
primary_or_secondary TEXT,
scenario_type TEXT,
direction TEXT,
zone_low NUMERIC(12,3),
zone_high NUMERIC(12,3),
trigger_conditions JSONB DEFAULT '[]'::jsonb,
invalidation_level NUMERIC(12,3),
tp_targets JSONB DEFAULT '[]'::jsonb,
h4_bias TEXT,
h1_bias TEXT,
dominant_bias TEXT,
bias_strength TEXT,
session_name TEXT,
psychological_level_context JSONB DEFAULT '[]'::jsonb,
market_condition TEXT,
status TEXT DEFAULT 'active',
created_at TIMESTAMPTZ DEFAULT NOW(),
resolved_at TIMESTAMPTZ,
final_outcome TEXT,
max_favorable_pips NUMERIC(12,2),
max_adverse_pips NUMERIC(12,2),
tp1_reached BOOLEAN DEFAULT FALSE,
tp2_reached BOOLEAN DEFAULT FALSE,
tp3_reached BOOLEAN DEFAULT FALSE,
notes TEXT
);

ALTER TABLE analyst_scenario_history
ADD COLUMN IF NOT EXISTS run_id BIGINT,
ADD COLUMN IF NOT EXISTS symbol TEXT DEFAULT 'XAUUSD',
ADD COLUMN IF NOT EXISTS scenario_key TEXT,
ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'live',
ADD COLUMN IF NOT EXISTS primary_or_secondary TEXT,
ADD COLUMN IF NOT EXISTS scenario_type TEXT,
ADD COLUMN IF NOT EXISTS direction TEXT,
ADD COLUMN IF NOT EXISTS zone_low NUMERIC(12,3),
ADD COLUMN IF NOT EXISTS zone_high NUMERIC(12,3),
ADD COLUMN IF NOT EXISTS trigger_conditions JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS invalidation_level NUMERIC(12,3),
ADD COLUMN IF NOT EXISTS tp_targets JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS h4_bias TEXT,
ADD COLUMN IF NOT EXISTS h1_bias TEXT,
ADD COLUMN IF NOT EXISTS dominant_bias TEXT,
ADD COLUMN IF NOT EXISTS bias_strength TEXT,
ADD COLUMN IF NOT EXISTS session_name TEXT,
ADD COLUMN IF NOT EXISTS psychological_level_context JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS market_condition TEXT,
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active',
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS final_outcome TEXT,
ADD COLUMN IF NOT EXISTS max_favorable_pips NUMERIC(12,2),
ADD COLUMN IF NOT EXISTS max_adverse_pips NUMERIC(12,2),
ADD COLUMN IF NOT EXISTS tp1_reached BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS tp2_reached BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS tp3_reached BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS notes TEXT;

CREATE TABLE IF NOT EXISTS analyst_confirmation_history (
id BIGSERIAL PRIMARY KEY,
run_id BIGINT,
symbol TEXT NOT NULL DEFAULT 'XAUUSD',
scenario_key TEXT,
confirmation_key TEXT,
source TEXT DEFAULT 'live',
scenario_type TEXT,
confirmation_type TEXT,
confirmation_grade TEXT,
confirmation_score NUMERIC(8,2),
direction TEXT,
level NUMERIC(12,3),
entry NUMERIC(12,3),
sl NUMERIC(12,3),
tp1 NUMERIC(12,3),
tp2 NUMERIC(12,3),
tp3 NUMERIC(12,3),
decision TEXT,
rejection_reason TEXT,
session_name TEXT,
timeframe TEXT,
created_at TIMESTAMPTZ DEFAULT NOW(),
final_outcome TEXT,
pips_result NUMERIC(12,2),
candidate_rank_score NUMERIC(8,2),
candidate_rank_reason TEXT,
tp1_hit BOOLEAN DEFAULT FALSE,
tp2_hit BOOLEAN DEFAULT FALSE,
tp3_hit BOOLEAN DEFAULT FALSE,
sl_hit BOOLEAN DEFAULT FALSE
);

ALTER TABLE analyst_confirmation_history
ADD COLUMN IF NOT EXISTS run_id BIGINT,
ADD COLUMN IF NOT EXISTS symbol TEXT DEFAULT 'XAUUSD',
ADD COLUMN IF NOT EXISTS scenario_key TEXT,
ADD COLUMN IF NOT EXISTS confirmation_key TEXT,
ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'live',
ADD COLUMN IF NOT EXISTS scenario_type TEXT,
ADD COLUMN IF NOT EXISTS confirmation_type TEXT,
ADD COLUMN IF NOT EXISTS confirmation_grade TEXT,
ADD COLUMN IF NOT EXISTS confirmation_score NUMERIC(8,2),
ADD COLUMN IF NOT EXISTS direction TEXT,
ADD COLUMN IF NOT EXISTS level NUMERIC(12,3),
ADD COLUMN IF NOT EXISTS entry NUMERIC(12,3),
ADD COLUMN IF NOT EXISTS sl NUMERIC(12,3),
ADD COLUMN IF NOT EXISTS tp1 NUMERIC(12,3),
ADD COLUMN IF NOT EXISTS tp2 NUMERIC(12,3),
ADD COLUMN IF NOT EXISTS tp3 NUMERIC(12,3),
ADD COLUMN IF NOT EXISTS decision TEXT,
ADD COLUMN IF NOT EXISTS rejection_reason TEXT,
ADD COLUMN IF NOT EXISTS session_name TEXT,
ADD COLUMN IF NOT EXISTS timeframe TEXT,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS final_outcome TEXT,
ADD COLUMN IF NOT EXISTS pips_result NUMERIC(12,2),
ADD COLUMN IF NOT EXISTS candidate_rank_score NUMERIC(8,2),
ADD COLUMN IF NOT EXISTS candidate_rank_reason TEXT,
ADD COLUMN IF NOT EXISTS tp1_hit BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS tp2_hit BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS tp3_hit BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS sl_hit BOOLEAN DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS analyst_trade_reviews (
id BIGSERIAL PRIMARY KEY,
run_id BIGINT,
setup_id TEXT,
symbol TEXT NOT NULL DEFAULT 'XAUUSD',
scenario_key TEXT,
scenario_type TEXT,
direction TEXT,
entry NUMERIC(12,3),
sl NUMERIC(12,3),
tp1 NUMERIC(12,3),
tp2 NUMERIC(12,3),
tp3 NUMERIC(12,3),
confirmation_type TEXT,
confirmation_grade TEXT,
learning_score NUMERIC(8,2),
candidate_rank_score NUMERIC(8,2),
reaction_level NUMERIC(12,3),
invalidation_level NUMERIC(12,3),
risk_pips NUMERIC(12,2),
tp1_reward_pips NUMERIC(12,2),
tp2_reward_pips NUMERIC(12,2),
tp3_reward_pips NUMERIC(12,2),
tp1_rr NUMERIC(12,2),
tp2_rr NUMERIC(12,2),
tp3_rr NUMERIC(12,2),
sl_source TEXT,
tp_source TEXT,
trade_path_source TEXT,
trade_path_rationale TEXT,
target_roles JSONB DEFAULT '{}'::jsonb,
setup_quality_label TEXT,
decision_reason TEXT,
session_name TEXT,
h4_bias TEXT,
h1_bias TEXT,
market_condition TEXT,
result TEXT,
pips_result NUMERIC(12,2),
tp1_hit BOOLEAN DEFAULT FALSE,
tp2_hit BOOLEAN DEFAULT FALSE,
tp3_hit BOOLEAN DEFAULT FALSE,
protected_after_tp1 BOOLEAN DEFAULT FALSE,
review_notes TEXT,
created_at TIMESTAMPTZ DEFAULT NOW(),
closed_at TIMESTAMPTZ
);

ALTER TABLE analyst_trade_reviews
ADD COLUMN IF NOT EXISTS run_id BIGINT,
ADD COLUMN IF NOT EXISTS setup_id TEXT,
ADD COLUMN IF NOT EXISTS symbol TEXT DEFAULT 'XAUUSD',
ADD COLUMN IF NOT EXISTS scenario_key TEXT,
ADD COLUMN IF NOT EXISTS scenario_type TEXT,
ADD COLUMN IF NOT EXISTS direction TEXT,
ADD COLUMN IF NOT EXISTS entry NUMERIC(12,3),
ADD COLUMN IF NOT EXISTS sl NUMERIC(12,3),
ADD COLUMN IF NOT EXISTS tp1 NUMERIC(12,3),
ADD COLUMN IF NOT EXISTS tp2 NUMERIC(12,3),
ADD COLUMN IF NOT EXISTS tp3 NUMERIC(12,3),
ADD COLUMN IF NOT EXISTS confirmation_type TEXT,
ADD COLUMN IF NOT EXISTS confirmation_grade TEXT,
ADD COLUMN IF NOT EXISTS learning_score NUMERIC(8,2),
ADD COLUMN IF NOT EXISTS candidate_rank_score NUMERIC(8,2),
ADD COLUMN IF NOT EXISTS reaction_level NUMERIC(12,3),
ADD COLUMN IF NOT EXISTS invalidation_level NUMERIC(12,3),
ADD COLUMN IF NOT EXISTS risk_pips NUMERIC(12,2),
ADD COLUMN IF NOT EXISTS tp1_reward_pips NUMERIC(12,2),
ADD COLUMN IF NOT EXISTS tp2_reward_pips NUMERIC(12,2),
ADD COLUMN IF NOT EXISTS tp3_reward_pips NUMERIC(12,2),
ADD COLUMN IF NOT EXISTS tp1_rr NUMERIC(12,2),
ADD COLUMN IF NOT EXISTS tp2_rr NUMERIC(12,2),
ADD COLUMN IF NOT EXISTS tp3_rr NUMERIC(12,2),
ADD COLUMN IF NOT EXISTS sl_source TEXT,
ADD COLUMN IF NOT EXISTS tp_source TEXT,
ADD COLUMN IF NOT EXISTS trade_path_source TEXT,
ADD COLUMN IF NOT EXISTS trade_path_rationale TEXT,
ADD COLUMN IF NOT EXISTS target_roles JSONB DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS setup_quality_label TEXT,
ADD COLUMN IF NOT EXISTS decision_reason TEXT,
ADD COLUMN IF NOT EXISTS session_name TEXT,
ADD COLUMN IF NOT EXISTS h4_bias TEXT,
ADD COLUMN IF NOT EXISTS h1_bias TEXT,
ADD COLUMN IF NOT EXISTS market_condition TEXT,
ADD COLUMN IF NOT EXISTS result TEXT,
ADD COLUMN IF NOT EXISTS pips_result NUMERIC(12,2),
ADD COLUMN IF NOT EXISTS tp1_hit BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS tp2_hit BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS tp3_hit BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS protected_after_tp1 BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS review_notes TEXT,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_analyst_replay_runs_started_at
ON analyst_replay_runs(started_at DESC);

CREATE INDEX IF NOT EXISTS idx_analyst_scenario_history_key
ON analyst_scenario_history(scenario_key);

CREATE INDEX IF NOT EXISTS idx_analyst_scenario_history_run
ON analyst_scenario_history(run_id);

CREATE INDEX IF NOT EXISTS idx_analyst_confirmation_history_key
ON analyst_confirmation_history(confirmation_key);

CREATE INDEX IF NOT EXISTS idx_analyst_confirmation_history_run
ON analyst_confirmation_history(run_id);

CREATE INDEX IF NOT EXISTS idx_analyst_trade_reviews_setup
ON analyst_trade_reviews(setup_id);

CREATE INDEX IF NOT EXISTS idx_analyst_trade_reviews_run
ON analyst_trade_reviews(run_id);

NOTIFY pgrst, 'reload schema';
