import { useMemo, useState, type ReactNode, type SelectHTMLAttributes } from "react"
import { Bell, Bot, Clock3, Layers3, Radio, ShieldCheck, SlidersHorizontal, Sparkles, Target } from "lucide-react"
import { cn } from "@/lib/utils"
import { BotControlPanel } from "@/components/control/BotControlPanel"
import { ReplayRunner } from "@/components/control/ReplayRunner"
import { SpencerStatus } from "@/components/control/SpencerStatus"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Separator } from "@/components/ui/separator"
import { Switch } from "@/components/ui/switch"
import { useBotStatus } from "@/hooks/use-data"

type StrategyMode = "auto" | "manual" | "hybrid"
type BiasRule = "strong only" | "strong + moderate" | "directional only"
type ConfirmationType = "liquidity_sweep_reclaim"
type Session = "asia" | "london" | "new_york"

type SettingsState = {
  strategyMode: StrategyMode
  activeSymbols: string
  allowedSessions: Session[]
  biasRule: BiasRule
  confirmationType: ConfirmationType
  moveSlToBeAfterTp1: boolean
  beOffsetPips: string
  enableAlerts: boolean
  enableTelegram: boolean
  telegramChannel: string
  enableManualSetupTracking: boolean
  enableAutoGeneratedSignals: boolean
  hybridRequireManualApproval: boolean
  hybridMaxConcurrentManualSetups: string
}

const DEFAULT_SETTINGS: SettingsState = {
  strategyMode: "hybrid",
  activeSymbols: "XAUUSD",
  allowedSessions: ["london", "new_york"],
  biasRule: "strong + moderate",
  confirmationType: "liquidity_sweep_reclaim",
  moveSlToBeAfterTp1: true,
  beOffsetPips: "0.0",
  enableAlerts: true,
  enableTelegram: true,
  telegramChannel: "@fxunfiltered",
  enableManualSetupTracking: true,
  enableAutoGeneratedSignals: true,
  hybridRequireManualApproval: true,
  hybridMaxConcurrentManualSetups: "5",
}

const SESSION_OPTIONS: Session[] = ["asia", "london", "new_york"]
const MODE_OPTIONS: StrategyMode[] = ["auto", "manual", "hybrid"]
const BIAS_OPTIONS: BiasRule[] = ["strong only", "strong + moderate", "directional only"]

export default function Settings() {
  const [settings, setSettings] = useState<SettingsState>(DEFAULT_SETTINGS)
  const botStatus = useBotStatus()

  function updateField<K extends keyof SettingsState>(key: K, value: SettingsState[K]) {
    setSettings((current) => ({ ...current, [key]: value }))
  }

  const modeBadge = useMemo(() => {
    if (settings.strategyMode === "auto") return { variant: "gold" as const, label: "Auto Mode" }
    if (settings.strategyMode === "manual") return { variant: "outline" as const, label: "Manual Mode" }
    return { variant: "purple" as const, label: "Hybrid Mode" }
  }, [settings.strategyMode])

  return (
    <div className="space-y-5 p-4 md:p-6">
      <div className="fixed inset-x-0 top-0 h-44 bg-glow-purple-top pointer-events-none" />
      <div className="fixed inset-x-0 top-0 h-28 bg-glow-gold-top pointer-events-none" />

      <div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between">
        <div className="space-y-1">
          <div className="inline-flex items-center gap-2 rounded-full border border-gold-500/20 bg-gold-500/8 px-3 py-1 text-[11px] font-semibold text-gold-300">
            <SlidersHorizontal className="h-3.5 w-3.5" />
            FX Unfiltered Control Center
          </div>
          <h1 className="text-xl font-bold text-foreground md:text-2xl">Settings</h1>
          <p className="max-w-2xl text-sm text-muted-foreground">
            Configure AlphaPulse strategy preferences, Spencer runtime behavior, alerts, manual tracking, and replay control from one place.
          </p>
        </div>

        <div className="grid grid-cols-2 gap-3 md:grid-cols-4">
          <MetricTile label="Strategy Mode" value={settings.strategyMode} accent="gold" icon={Bot} />
          <MetricTile label="Active Sessions" value={String(settings.allowedSessions.length)} accent="muted" icon={Clock3} />
          <MetricTile label="Alerts" value={settings.enableAlerts ? "On" : "Off"} accent={settings.enableAlerts ? "buy" : "muted"} icon={Bell} />
          <MetricTile label="Tracking" value={settings.enableManualSetupTracking ? "Ready" : "Off"} accent="gold" icon={Layers3} />
        </div>
      </div>

      <SpencerStatus status={botStatus.data} />

      <div className="grid gap-4 xl:grid-cols-[1.05fr_0.95fr]">
        <BotControlPanel />
        <ReplayRunner />
      </div>

      <Card>
        <CardContent className="flex flex-col gap-4 py-4 lg:flex-row lg:items-center lg:justify-between">
          <div className="space-y-1">
            <div className="label-xs">Current Active Strategy</div>
            <div className="text-sm font-semibold text-foreground">FX Unfiltered · Gap + Sweep Reclaim</div>
            <div className="text-xs text-muted-foreground">Powered by AlphaPulse with Spencer as the user-facing assistant.</div>
          </div>
          <div className="flex flex-wrap gap-2">
            <Badge variant={modeBadge.variant} className="text-[10px]">{modeBadge.label}</Badge>
            <Badge variant="gold" className="text-[10px]">liquidity sweep reclaim</Badge>
            <Badge variant="outline" className="text-[10px]">{settings.biasRule}</Badge>
          </div>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 gap-5 2xl:grid-cols-12">
        <div className="space-y-5 2xl:col-span-7">
          <SettingsPanel title="Strategy Mode" description="Switch between automated, manual, or hybrid control." icon={Bot}>
            <div className="grid gap-3 md:grid-cols-3">
              {MODE_OPTIONS.map((mode) => (
                <ModeCard
                  key={mode}
                  active={settings.strategyMode === mode}
                  label={mode}
                  description={
                    mode === "auto"
                      ? "Spencer runs the live strategy automatically."
                      : mode === "manual"
                      ? "Only manual setups and operator decisions are tracked."
                      : "Blend Spencer signals with manual review and setup tracking."
                  }
                  onClick={() => updateField("strategyMode", mode)}
                />
              ))}
            </div>
          </SettingsPanel>

          <SettingsPanel title="Strategy Rules" description="Active symbols, sessions, bias rules, and confirmation settings." icon={Target}>
            <div className="grid gap-4 md:grid-cols-2">
              <Field label="Active Symbol(s)">
                <Input value={settings.activeSymbols} onChange={(e) => updateField("activeSymbols", e.target.value)} placeholder="XAUUSD" />
              </Field>
              <Field label="Bias Rules">
                <Select value={settings.biasRule} onChange={(e) => updateField("biasRule", e.target.value as BiasRule)}>
                  {BIAS_OPTIONS.map((option) => (
                    <option key={option} value={option}>{option}</option>
                  ))}
                </Select>
              </Field>
              <Field label="Active Confirmation Type">
                <Select value={settings.confirmationType} onChange={(e) => updateField("confirmationType", e.target.value as ConfirmationType)}>
                  <option value="liquidity_sweep_reclaim">liquidity sweep reclaim</option>
                </Select>
              </Field>
              <Field label="Active Strategy Display">
                <Input value="Gap + Sweep Reclaim Only" readOnly />
              </Field>
            </div>

            <Separator />

            <div className="space-y-3">
              <div className="label-xs">Allowed Sessions</div>
              <div className="grid gap-3 sm:grid-cols-3">
                {SESSION_OPTIONS.map((session) => {
                  const active = settings.allowedSessions.includes(session)
                  return (
                    <button
                      key={session}
                      type="button"
                      onClick={() => {
                        const next = active ? settings.allowedSessions.filter((item) => item !== session) : [...settings.allowedSessions, session]
                        updateField("allowedSessions", next)
                      }}
                      className={cn(
                        "rounded-xl border px-4 py-3 text-left transition-all",
                        active ? "border-gold-500/30 bg-gold-500/10 text-foreground" : "border-ap-border bg-ap-surface/35 text-muted-foreground hover:text-foreground"
                      )}
                    >
                      <div className="text-sm font-semibold capitalize text-foreground">{formatSession(session)}</div>
                      <div className="mt-1 text-[11px]">{active ? "Enabled for active scanning" : "Currently excluded"}</div>
                    </button>
                  )
                })}
              </div>
            </div>
          </SettingsPanel>

          <SettingsPanel title="TP / BE Rules" description="Manage first-target behavior and break-even protection." icon={ShieldCheck}>
            <div className="grid gap-4 md:grid-cols-2">
              <ToggleCard
                label="Move SL to BE after TP1"
                description="Protect remaining size automatically once TP1 is hit."
                checked={settings.moveSlToBeAfterTp1}
                onCheckedChange={(checked) => updateField("moveSlToBeAfterTp1", checked)}
              />
              <Field label="BE Offset (pips)">
                <Input className="num" value={settings.beOffsetPips} onChange={(e) => updateField("beOffsetPips", e.target.value)} placeholder="0.0" />
              </Field>
            </div>
          </SettingsPanel>
        </div>

        <div className="space-y-5 2xl:col-span-5">
          <SettingsPanel title="Telegram Settings" description="Alert delivery and channel routing controls." icon={Bell}>
            <div className="space-y-3">
              <ToggleCard
                label="Enable Alerts"
                description="Turn the alert pipeline on or off for all delivery channels."
                checked={settings.enableAlerts}
                onCheckedChange={(checked) => updateField("enableAlerts", checked)}
              />
              <ToggleCard
                label="Enable Telegram"
                description="Deliver active bot and trade notifications to Telegram."
                checked={settings.enableTelegram}
                onCheckedChange={(checked) => updateField("enableTelegram", checked)}
              />
              <Field label="Telegram Channel">
                <Input value={settings.telegramChannel} onChange={(e) => updateField("telegramChannel", e.target.value)} placeholder="@fxunfiltered" />
              </Field>
            </div>
          </SettingsPanel>

          <SettingsPanel title="Manual Mode Settings" description="Controls for discretionary setups and operator-led flow." icon={Radio}>
            <div className="space-y-3">
              <ToggleCard
                label="Enable Manual Setup Tracking"
                description="Allow the manual setups page to feed tracking-ready items."
                checked={settings.enableManualSetupTracking}
                onCheckedChange={(checked) => updateField("enableManualSetupTracking", checked)}
              />
              <ToggleCard
                label="Enable Auto-Generated Signals"
                description="Let Spencer continue generating signals while manual tracking remains active."
                checked={settings.enableAutoGeneratedSignals}
                onCheckedChange={(checked) => updateField("enableAutoGeneratedSignals", checked)}
              />
            </div>
          </SettingsPanel>

          <SettingsPanel title="Hybrid Mode Settings" description="Blend automated signals with manual approval and oversight." icon={Sparkles}>
            <div className="space-y-3">
              <ToggleCard
                label="Hybrid Require Manual Approval"
                description="Hold generated setups until a manual approval action is taken."
                checked={settings.hybridRequireManualApproval}
                onCheckedChange={(checked) => updateField("hybridRequireManualApproval", checked)}
              />
              <Field label="Max Concurrent Manual Setups">
                <Input
                  className="num"
                  value={settings.hybridMaxConcurrentManualSetups}
                  onChange={(e) => updateField("hybridMaxConcurrentManualSetups", e.target.value)}
                  placeholder="5"
                />
              </Field>
            </div>
          </SettingsPanel>
        </div>
      </div>
    </div>
  )
}

function MetricTile({
  label,
  value,
  accent,
  icon: Icon,
}: {
  label: string
  value: string
  accent: "gold" | "buy" | "muted"
  icon: typeof Bot
}) {
  const color = accent === "buy" ? "text-buy" : accent === "gold" ? "text-gold-300" : "text-foreground"
  const bg = accent === "buy" ? "border-buy/20 bg-buy/8" : accent === "gold" ? "border-gold-500/20 bg-gold-500/8" : "border-ap-border bg-ap-surface/35"

  return (
    <Card>
      <CardContent className="flex items-center gap-3 py-4">
        <div className={cn("flex h-10 w-10 items-center justify-center rounded-lg border", bg)}>
          <Icon className={cn("h-4 w-4", color)} />
        </div>
        <div>
          <div className="label-xs">{label}</div>
          <div className={cn("mt-1 text-sm font-semibold capitalize", color)}>{value}</div>
        </div>
      </CardContent>
    </Card>
  )
}

function SettingsPanel({
  title,
  description,
  icon: Icon,
  children,
}: {
  title: string
  description: string
  icon: typeof Bot
  children: ReactNode
}) {
  return (
    <Card glow>
      <CardHeader className="pb-3">
        <div className="flex items-start gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg border border-gold-500/20 bg-gold-500/8">
            <Icon className="h-4 w-4 text-gold-300" />
          </div>
          <div>
            <CardTitle>{title}</CardTitle>
            <CardDescription>{description}</CardDescription>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-4 pt-0">{children}</CardContent>
      <CardFooter className="justify-end">
        <Button size="sm">Save Mock Settings</Button>
      </CardFooter>
    </Card>
  )
}

function ModeCard({
  active,
  label,
  description,
  onClick,
}: {
  active: boolean
  label: StrategyMode
  description: string
  onClick: () => void
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={cn(
        "rounded-xl border p-4 text-left transition-all",
        active ? "border-gold-500/30 bg-gold-500/10 shadow-gold-xs" : "border-ap-border bg-ap-surface/35 hover:bg-ap-surface/55"
      )}
    >
      <div className="flex items-center justify-between gap-3">
        <span className="text-sm font-semibold capitalize text-foreground">{label}</span>
        <Badge variant={active ? "gold" : "muted"} className="text-[10px]">{active ? "Active" : "Available"}</Badge>
      </div>
      <p className="mt-2 text-xs leading-6 text-muted-foreground">{description}</p>
    </button>
  )
}

function Field({ label, children }: { label: string; children: ReactNode }) {
  return (
    <div className="space-y-1.5">
      <label className="label-xs">{label}</label>
      {children}
    </div>
  )
}

function Select(props: SelectHTMLAttributes<HTMLSelectElement>) {
  return (
    <select
      {...props}
      className={cn(
        "flex h-9 w-full rounded-md border border-ap-border bg-ap-surface px-3 py-1 text-sm text-foreground",
        "focus:border-gold-500 focus:outline-none focus:ring-2 focus:ring-ring",
        props.className
      )}
    />
  )
}

function ToggleCard({
  label,
  description,
  checked,
  onCheckedChange,
}: {
  label: string
  description: string
  checked: boolean
  onCheckedChange: (checked: boolean) => void
}) {
  return (
    <div className="flex items-start justify-between gap-3 rounded-xl border border-ap-border bg-ap-surface/35 px-4 py-3">
      <div>
        <p className="text-sm font-medium text-foreground">{label}</p>
        <p className="mt-1 text-xs leading-6 text-muted-foreground">{description}</p>
      </div>
      <Switch checked={checked} onCheckedChange={onCheckedChange} />
    </div>
  )
}

function formatSession(value: Session) {
  return value === "new_york" ? "New York" : value.charAt(0).toUpperCase() + value.slice(1)
}
